=== diego75/lmsgi/UT5/xsd/12-personas.xsd
<?xml version='1.0' encoding='UTF-8'?>

<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'
targetNamespace='http://www.iescierva.net'
xmlns='http://www.iescierva.net' elementFormDefault='qualified'>

<xs:element name='personas'>
  <xs:complexType>
    <xs:sequence>

<xs:element name='persona'  minOccurs='1' maxOccurs='unbounded'>
  <xs:complexType>
    <xs:sequence>
      <xs:attribute name='nombre' type='nombre' />
      <xs:element name='apellidos'>
          <xs:simpleType>
    		<xs:restriction base='xs:string'>
      			<xs:pattern value='[a-zA-ZáéíóúÁÉÍÓÚüÜçÇ -]{1,30}'/>
    		</xs:restriction>
          </xs:simpleType>
      </xs:element>
      <xs:element name='fnac' type='xs:date' />
      <xs:choice minOccurs='0' maxOccurs='10'>
	      <xs:element name='email'>
          	<xs:simpleType>
    			<xs:restriction base='xs:string'>
      				<xs:pattern value='[a-zA-Z_.-][a-zA-Z0-9_.-]*@[a-zA-Z0-9_.-]+'/>
    			</xs:restriction>
	          </xs:simpleType>
    	  </xs:element>
      	  <xs:element name='teléfono'>
          	<xs:simpleType>
    			<xs:restriction base='xs:string'>
      				<xs:pattern value='[+0-9 _.-]{3,20}'/>
    			</xs:restriction>
          	</xs:simpleType>
      	  </xs:element>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
</xs:element>

    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:simpleType name='nombre'>
  <xs:restriction base='xs:string'>
    <xs:pattern value='[a-zA-ZáéíóúÁÉÍÓÚüÜçÇ ]{1,20}'/>
  </xs:restriction>
</xs:simpleType>

</xs:schema>

=== diego75/lmsgi/UT5/12-personas.xml
<?xml version='1.0' encoding='UTF-8' standalone='no' ?>

<personas
xmlns='http://www.iescierva.net'
xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
xsi:schemaLocation='http://www.iescierva.net xsd/12-personas.xsd'>

<persona>
		<nombre>Pepe</nombre>
		<apellidos>Gómez Martínez</apellidos>
		<fnac>2012-01-23</fnac>
		<email>pepe@gmail.com</email>
</persona>

<persona>
		<nombre>Mariconchi</nombre>
		<apellidos>Ruíz de la Borbolla</apellidos>
		<fnac>2000-01-13</fnac>
		<teléfono>0034-968-433-1111</teléfono>
		<email>mariconchi@hotmail.com</email>
		<email>mariconchi@gmail.com</email>
</persona>

</personas>
