=== diego75/lmsgi/Ejemplos/024-dtd con atributos.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!-- DTD mensaje -->

<!ELEMENT texto (#PCDATA)>
	<!ATTLIST texto idioma CDATA #REQUIRED>

<!ELEMENT de (#PCDATA)>

<!ELEMENT a (#PCDATA)>

<!ELEMENT mensaje (de,a,texto) >
	<!ATTLIST mensaje 
		prioridad (normal|urgente|baja) 'normal'
		fecha CDATA #REQUIRED 
		codpostal CDATA #FIXED '46110'
		resumen CDATA #IMPLIED >

<!ELEMENT mensajes ( (mensaje)* ) >

<!ELEMENT empleado (#PCDATA)>
	<!ATTLIST empleado
		dni ID #REQUIRED >

<!ELEMENT pais (#PCDATA)>
	<!ATTLIST pais
	   población NMTOKEN #REQUIRED >
	
<!ELEMENT teléfono (#PCDATA)>
	<!ATTLIST teléfono
	   lugar (oficina|móvil|particular) 'oficina'>
			
<!ELEMENT factura EMPTY>
	<!ATTLIST factura
		fecha CDATA #REQUIRED
		dni IDREF #REQUIRED >

=== diego75/lmsgi/Ejemplos/024-dtd con atributos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE mensajes SYSTEM "024-dtd con atributos.dtd">

<!-- ejemplo de mensaje -->

<mensajes>

<mensaje fecha="2011-02-23">
  <de>Josefa Gómez &lt;jgomez@yahoo.es&gt; </de>
  <a>Juan Martínez &lt;jmartinez@gmail.com&gt; </a>
  <texto idioma="es">Hola, que tal...</texto>
</mensaje>

<mensaje fecha="2011-02-23" prioridad='urgente' resumen='saludo' codpostal='46110' >
  <de>Juan Martínez &lt;jmartinez@gmail.com&gt; </de>
  <a>Josefa Gómez &lt;jgomez@yahoo.es&gt; </a>
  <texto idioma="es">Bien, ¿y tú?</texto>
</mensaje>

</mensajes>
