=== diego75/lmsgi/Ejemplos/116-figuras.xsd
<?xml version='1.0' encoding='UTF-8'?>

<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'
	targetNamespace='mi-espacio'
	xmlns='mi-espacio'
	elementFormDefault='qualified'>
	
<!-- ejemplo con extensiones -->

	<xs:element name='registro-figuras'>
		<xs:complexType>
			<xs:sequence>   <!--el orden es obligatorio -->
				<xs:element name='cuadrado' type='figura' />
				<xs:element name='cÃ­rculo' type='figuraExtendida' />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

  <xs:complexType name='figura'>
  	<xs:sequence>
  	  <xs:element name='nombre' type='xs:string' />
  	  <xs:element name='superficie' type='xs:string' />
  	</xs:sequence>
  </xs:complexType>
  
  <xs:complexType name='figuraExtendida'>
	<xs:complexContent>
  		<xs:extension base='figura'>
  			<xs:sequence>
  				<xs:element name='radio' type='xs:double' />
  				<xs:element name='longitud' type='xs:double' /> 						
	  		</xs:sequence>
  		</xs:extension>
  	</xs:complexContent>
  </xs:complexType>
  
</xs:schema>

=== diego75/lmsgi/Ejemplos/116-figuras.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>

<registro-figuras
  xmlns='mi-espacio'
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='mi-espacio 116-figuras.xsd' >

<cuadrado>
	<nombre>cuadrado rojo</nombre>
	<superficie>150 cm2</superficie>
</cuadrado>

<círculo>
	<nombre>círculo verde</nombre>
	<superficie>43 cm2</superficie>
	<radio>12.9</radio>
	<longitud>11.45</longitud>
</círculo>

</registro-figuras>
